kind: pipeline
name: node build

steps:
  -   name: node build
      image: node:14.10.0
      commands:
        - yarn config set registry https://registry.npm.taobao.org
        - yarn install
        - yarn run build
